// This file is auto-generated by TanStack Router CLI
// It will be regenerated when you run `vite` or `pnpm build`
// Do not edit manually

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRoute } from './routes/index'
import { Route as DashboardRoute } from './routes/dashboard'
import { Route as ActionsRoute } from './routes/actions'
import { Route as OpsRoute } from './routes/ops'
import { Route as ScorecardsRoute } from './routes/scorecards'
import { Route as CatalogIndexRoute } from './routes/catalog/index'
import { Route as CatalogEntityIdRoute } from './routes/catalog/$entityId'

const rootTree = rootRoute.addChildren([
  IndexRoute,
  DashboardRoute,
  ActionsRoute,
  OpsRoute,
  ScorecardsRoute,
  CatalogIndexRoute,
  CatalogEntityIdRoute,
])

export { rootTree as routeTree }
